Repository openshift/openstack-cinder-csi-driver-operator, pull requests merged in 2021-01, with the labels that each got.

#14 Bug 1902545: Only run driver-node on Linux workers
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#16 Bug 1902600: Set csi-snapshotter imagePullPolicy to IfNotPresent
  assets/controller.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#18 Bug 1902546: Allow cinder-csi-driver-node pods to run everywhere
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#22 Bug 1902547: Add Mike and Martin to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#23 Bug 1918140: Fix sync of config.openshift.io informer
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#24 Bug 1908998: add secret hash annotation hook to the controller
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
