Repository openshift/openstack-cinder-csi-driver-operator, pull requests merged in 2022-03, with the labels that each got.

#73 Bump gophercloud
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/.gitignore
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/README.md
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go
  vendor/golang.org/x/crypto/internal/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/internal/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/poly1305.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go
  vendor/modules.txt
Labels: approved, lgtm

#75 Set fsGroupPolicy in CSIDriver
  assets/csidriver.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#74 Bug 2061732: Fail gracefully on failure to populate cloud info
  pkg/operator/cloudinfo.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#77 Bug 2067869: Address CVE-2022-21698
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium
